GP: Duplicate meta descriptions
jsdelivr/www.jsdelivr.com pull request #716
Opened 2024-12-17 14:05 UTC by xbpcb

Fix #715

2024-12-17 14:10 UTC, xbpcb commented
In-progress.
There is an issue with Network-tools meta descriptions and Google.
I'm working on it.

2024-12-19 17:02 UTC, MartinKolarik commented on src/views/pages/globalping/network-tools.html
>  	const PROBE_STATUS_OFFLINE = _.getProbeStatusOfflineValue();
What exactly was broken on these pages and how does it change?

2024-12-19 17:02 UTC, MartinKolarik commented on src/views/pages/globalping/network-tools.html
> +			titleAndDescr () {
I don't understand why this was moved to be a computed property if it's still used just once during the load.

2024-12-19 17:53 UTC, xbpcb commented
There's another problem - we have several pairs of different URLs pointing to the same page, such as /ping and /ping-from-world, /http and /http-from-world, and so on.
They share the same meta description which might cause the same issue with Google.

2024-12-30 14:23 UTC, MartinKolarik requested changes
`/network-tools/http-from-amazoncom-inc` doesn't work now.

2024-12-30 15:03 UTC, MartinKolarik commented on src/routes/globalping.js
> -	[ '/network-tools', '/network-tools/:params?' ],
This was ok before, the first value is just a name reported in APM.

2025-01-02 15:51 UTC, MartinKolarik approved these changes

2025-01-02 16:06 UTC, merged